# Generated by Django 5.2.5 on 2025-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterprofile',
            name='cert_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
