# Generated by Django 5.2.5 on 2025-09-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawsitting', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='sitterprofile',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sitterprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SitterProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
